### DISCUSSION TITLE
Improvement Proposal: Schedules for Playbook Configurations (Events)

### DISCUSSION THREAD

**Discussion by ubaniabalogun** [twilio-labs/sls-apb#22] [Ideas]
# Challenge
SOCless is on the path to supporting direct invocation of Playbook. One of features this enables us benefit from is direct scheduling of playbooks using AWS EventBridge. Currently, directly scheduling a playbook via EventBridge requires manually creating a Resource in your serverless.yml as shown below:

**serverless.yml**
```
custom:
    playbooks:
          - scheduled_playbook

resources:
  Resources:
    EventRuleTestSchedule:
      Type: AWS::Events::Rule
      Properties:
        Description: Execute EventsRuleTestSchedule
        ScheduleExpression: rate(1 minute)
        State: ENABLED
        Targets:
          -
            Arn:
              Ref: ScheduledPlaybook
            Id: RuleIdentifier
            RoleArn: ${{cf:socless-${{self:provider.stage}}.StatesExecutionRoleArn}} <--- role in SOCless core stack
            Input: {}
```

Tis quite a lot to get right. 

# Proposed Solution
The proposed solution entails supporting configuration options for playbooks, one of which is an `events` list that can include schedules as shown below

**serverless.yml**
```
custom:
    playbooks:
          - unscheduled_playbook
          - scheduled_playbook:
                   events:
                        - schedule:
                               rate: rate(1 minute)
                               enabled: true
                               input: {}
```

sls-apb would read the following config on the `playbooks` object then render the appropriate `Resource` with reasonable defaults, similar to how it renders StateMachine CF Resource.

Note: The feature may support more keys than shown above

The syntax above is heavily inspired by the existing [events schedule](https://www.serverless.com/framework/docs/providers/aws/events/schedule/) syntax provided by the serverless framework for adding Events to lambda

# Considered Alternatives

The below alternative was considered (i.e. leaving `events` off and adding `schedule` directly to the playbook

```
custom:
    playbooks:
          - unscheduled_playbook
          - scheduled_playbook:
                 - schedule:
                       rate: rate(1 minute)
                       enabled: true
                       input: {}
```

However, the `events` parent section is favored as it enables adding other types of non-event, playbook-specific configurations in the future

# Backward Compatibility Considerations
The Feature is expected to be implementable without breaking existing configurations
